# Generated by Django 5.2.7 on 2025-10-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='accounts.section'),
        ),
        migrations.AddField(
            model_name='floor',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='accounts.subsection'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('title', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'department')},
        ),
    ]
