# Generated by Django 5.2.7 on 2025-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
