# Generated by Django 5.2.7 on 2025-11-16 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_line_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='department',
            name='company_unit',
        ),
        migrations.RemoveField(
            model_name='department',
            name='group',
        ),
        migrations.RemoveField(
            model_name='division',
            name='group',
        ),
        migrations.AddField(
            model_name='companyunit',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='company_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='accounts.companyunit'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='accounts.section'),
        ),
        migrations.AlterModelTable(
            name='section',
            table=None,
        ),
        migrations.RemoveField(
            model_name='floor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='section',
            name='updated_at',
        ),
    ]
