# Generated by Django 5.2.7 on 2025-10-22 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyunit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_units', to='accounts.customgroup'),
        ),
    ]
