# Generated by Django 5.2.7 on 2025-10-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyunit_floor_group_division_companyunit_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_dept', to='accounts.division')),
            ],
        ),
        migrations.CreateModel(
            name='SectiotSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_sec', to='accounts.department')),
            ],
        ),
    ]
