# Generated by Django 5.2.7 on 2025-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_companyunit_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
