# Generated by Django 5.2.7 on 2025-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_companyunit_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
