# Generated by Django 5.2.7 on 2025-10-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_division_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='company_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyunit'),
        ),
    ]
