# Generated by Django 5.2.7 on 2025-10-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_division_code_division_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.RemoveField(
            model_name='department',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='department',
            name='company_unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.companyunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.customgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.division'),
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
    ]
