# Generated by Django 5.2.7 on 2025-10-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_department_options_remove_department_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyunit',
            name='group',
        ),
    ]
