# Generated by Django 5.2.7 on 2025-10-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_companyunit_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyunit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_units', to='accounts.customgroup'),
        ),
    ]
