# Generated by Django 5.2.7 on 2025-10-31 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_companyunit_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsection',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='subsection',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section'),
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together={('name', 'section')},
        ),
    ]
