# Generated by Django 5.2.7 on 2025-11-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_line_is_active'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.floor'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.line'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='accounts.subsection'),
        ),
    ]
