# Generated by Django 5.2.7 on 2025-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_department_alter_employee_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='weekend',
            field=models.CharField(blank=True, choices=[('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday')], default='FRIDAY', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
