# Generated by Django 5.2.7 on 2025-10-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_attendance_bonus_employee_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='food_deduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='late_deduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pF_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_deduct',
            field=models.BooleanField(default=False),
        ),
    ]
