# Generated by Django 5.2.7 on 2025-10-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_board_employee_degree_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationrecord',
            name='certificate',
        ),
        migrations.AddField(
            model_name='employee',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
