# Generated by Django 5.2.7 on 2025-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_educationrecord_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duration_Month',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='institue_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='score',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='training_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
