# Generated by Django 5.2.7 on 2025-10-20 05:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_duration_month_employee_institue_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(default='Bangladesh', max_length=2),
        ),
    ]
