# Generated by Django 5.2.7 on 2025-10-20 12:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=django_countries.fields.CountryField(default='BD', max_length=2),
        ),
    ]
