# Generated by Django 5.2.7 on 2025-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender1',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
