# Generated by Django 5.2.7 on 2025-10-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_gender1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gender1',
            new_name='blood_group1',
        ),
    ]
