# Generated by Django 5.2.7 on 2025-10-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_rename_gender1_employee_blood_group1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blood_group1',
        ),
    ]
