# Generated by Django 5.2.7 on 2025-10-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_employee_blood_group1'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blood_grp',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='', max_length=10),
        ),
    ]
