# Generated by Django 4.2.7 on 2025-10-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_contribution_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employer_contribution_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provident_fund', to='employees.employee')),
            ],
        ),
    ]
